/** Timing constants extracted from ai_commands.js. */
const HOTKEY_LINE_DELAY_MS = 100;
const KEYBINDING_DEBOUNCE_MS = 200;
const SETTINGS_TIMEOUT_MS = 2000;
const HOTKEY_RESET_TIMEOUT_MS = 10000; // fallback if the normal reset fails
const STATUS_MESSAGE_DURATION_MS = 1500;
const ERROR_MESSAGE_TIMEOUT_MS = 30000;
const KILL_SCRIPT_INFO_TIMEOUT_MS = 10000;
const NO_BREAK_SPACE = '\u00A0';
const OUTPUT_NAME_TEMPLATE = 'extension-output-${publisher}.${name}-#';

export {
  HOTKEY_LINE_DELAY_MS,
  KEYBINDING_DEBOUNCE_MS,
  SETTINGS_TIMEOUT_MS,
  HOTKEY_RESET_TIMEOUT_MS,
  STATUS_MESSAGE_DURATION_MS,
  ERROR_MESSAGE_TIMEOUT_MS,
  KILL_SCRIPT_INFO_TIMEOUT_MS,
  NO_BREAK_SPACE,
  OUTPUT_NAME_TEMPLATE,
};
